version: "3.7"
services:
  postgres:
    image: postgres:17
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: administrator
      POSTGRES_DB: products
  product-service:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
