export enum ReportTypeEnum {
  DELETED_PRODUCTS_PERCENTAGE = 'DELETED_PRODUCTS_PERCENTAGE',
  NON_DELETED_PRODUCTS_PERCENTAGE = 'NON_DELETED_PRODUCTS_PERCENTAGE',
  CUSTOM_CATEGORIES_PERCENTAGE = 'CUSTOM_CATEGORIES_PERCENTAGE',
}
